// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create a firebase project and run the FlutterFire CLI command to get the configuration',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: This is a placeholder with dummy values - replace with your real configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT76wVm9cEuUV1NoxcGeSoFWVR9c2-_eM',
    appId: '1:152671122222:android:834896c57ce00ead5280bf',
    messagingSenderId: '152671122222',
    projectId: 'nutrizen-3f0b8',
    storageBucket: 'nutrizen-3f0b8.firebasestorage.app',
  );

  // You'll need to run flutterfire configure to generate proper values

  // NOTE: This is a placeholder with dummy values - replace with your real configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Qrt1-ny5CFtZFRZ1KRQ5Ecwn2wyMjjw',
    appId: '1:152671122222:ios:dd624ba71599fcf15280bf',
    messagingSenderId: '152671122222',
    projectId: 'nutrizen-3f0b8',
    storageBucket: 'nutrizen-3f0b8.firebasestorage.app',
    iosBundleId: 'com.example.foodAiApp',
  );

  // You'll need to run flutterfire configure to generate proper values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVzU4TEzKtPDAFzw7qSA5V-9oQz6XiRvw',
    appId: '1:152671122222:web:70bce4713ecf868e5280bf',
    messagingSenderId: '152671122222',
    projectId: 'nutrizen-3f0b8',
    authDomain: 'nutrizen-3f0b8.firebaseapp.com',
    storageBucket: 'nutrizen-3f0b8.firebasestorage.app',
    measurementId: 'G-DEQTLZQWWL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Qrt1-ny5CFtZFRZ1KRQ5Ecwn2wyMjjw',
    appId: '1:152671122222:ios:dd624ba71599fcf15280bf',
    messagingSenderId: '152671122222',
    projectId: 'nutrizen-3f0b8',
    storageBucket: 'nutrizen-3f0b8.firebasestorage.app',
    iosBundleId: 'com.example.foodAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVzU4TEzKtPDAFzw7qSA5V-9oQz6XiRvw',
    appId: '1:152671122222:web:2da31362c98e4ba65280bf',
    messagingSenderId: '152671122222',
    projectId: 'nutrizen-3f0b8',
    authDomain: 'nutrizen-3f0b8.firebaseapp.com',
    storageBucket: 'nutrizen-3f0b8.firebasestorage.app',
    measurementId: 'G-2ZCPWWRXYM',
  );

}